// Generated by https://quicktype.io
// Generated by https://quicktype.io

export interface LoginResponse {
  token: string;
  user:  User;
}

export interface User {
  uid:            string;
  name:           string;
  email:          string;
  changePassword: boolean;
}

export interface LoginData {
  email:    string;
  password: string;
}
// Generated by https://quicktype.io

export interface RegisterData {
  name:        string;
  dni:         string;
  email:       string;
  password:    string;
}
