// Generated by https://quicktype.io

export interface BankResponse {
  banks:    Bank[];
  accountTypes: string[];
}

export interface Bank {
  _id:        string;
  name:       string;
  internalId: string;
  createdAt?: string;
  updatedAt?: string;
}

// Generated by https://quicktype.io

export interface DestinataryResponse {
  destinataries: Destinatary[];
}

export interface Destinatary {
  _id?:           string;
  name:          string;
  dni:           string;
  email:         string;
  phoneNumber:   string;
  bankId:        string | BankID;
  accountType:   string;
  accountNumber: string;
  userId?:        string;
  createdAt?:     string;
  updatedAt?:     string;
}

export interface BankID {
  _id:  string;
  name: string;
}

// Generated by https://quicktype.io

export interface MovementResponse {
  movements: Movement[];
}

export interface Movement {
  _id:           string;
  userId:        string;
  destinataryId: DestinataryID;
  amount:        number;
  createdAt:     string;
  updatedAt:     string;
}

export interface DestinataryID {
  _id:         string;
  name:        string;
  dni:         string;
  bankId:      BankID;
  accountType: string;
}

export interface BankID {
  _id:  string;
  name: string;
}

// Generated by https://quicktype.io

export interface MovementRequest {
  destinataryId: string;
  amount:        number;
}
